# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20160803_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books', models.ManyToManyField(null=True, to='bookstore.Book')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.User')),
            ],
        ),
    ]
