# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_user_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_wishlist',
            name='books',
            field=models.ManyToManyField(to='bookstore.Book'),
        ),
    ]
